sudo: false
language: node_js
branches:
  only:
    - master
matrix:
  fast_finish: true
  include:
    - os: linux
      node_js: '7'
      env: WEBPACK_VERSION="2.2.0" JOB_PART=lint
    - os: linux
      node_js: '4.3'
      env: WEBPACK_VERSION="2.2.0" JOB_PART=test
    - os: linux
      node_js: '6'
      env: WEBPACK_VERSION="2.2.0" JOB_PART=test
    - os: linux
      node_js: '7'
      env: WEBPACK_VERSION="2.2.0" JOB_PART=coverage
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
  - nvm --version
  - node --version
  - export CXX=g++
  - export CC=gcc
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX=g++-4.8; fi
before_script:
  - |-
    if [ "$WEBPACK_VERSION" ]; then
      yarn add webpack@^$WEBPACK_VERSION
    fi
script:
  - npm rebuild node-zopfli
  - 'yarn run travis:$JOB_PART'
after_success:
  - 'bash <(curl -s https://codecov.io/bash)'
